name: Build Program
run-name: Building the program
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Auto-formatting
        run: make format
        
      - name: Checking codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code
    
      - name: Build application
        run: make

      - name: Build & run tests
        run: make test
