name: Build Program
run-name: Building the program
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build application
        run: make

      - name: Build & run tests
        run: make test
